CREATE DATABASE TEST;
CREATE TABLE BAL_TABLE(USERNAME VARCHAR(40),ACCNUM VARCHAR(12), BALANCE VARCHAR(20));

CREATE TABLE BANK_OP(FULLNAME VARCHAR(40),EMAIL VARCHAR(50),USERNAME VARCHAR(40),PASSWORD VARCHAR(30),PHNUMBER VARCHAR(10),ADDRESS VARCHAR(150),ACCNUM VARCHAR(12));

CREATE TABLE TRANS(FROM_USER VARCHAR(40),TO_USER VARCHAR(40),DATE_AND_TIME VARCHAR(50),METHOD VARCHAR(20),AMOUNT VARCHAR(20),DOT DATE,STATUS VARCHAR(20));
